# Generated by Django 5.0.1 on 2024-02-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
