# Generated by Django 5.0.1 on 2024-02-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
