# Generated by Django 5.0.1 on 2024-02-06 22:49

import django.core.validators
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='product_images/', validators=[django.core.validators.validate_image_file_extension, product.models.validate_image_content]),
        ),
    ]
