# Generated by Django 5.0.1 on 2024-02-09 00:17

import django.core.validators
import product.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_ratings_alter_review_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(default='images/products/default.jpeg', upload_to='product_images/', validators=[django.core.validators.validate_image_file_extension, product.utils.validate_image_content]),
        ),
    ]
