# Generated by Django 5.0.1 on 2024-02-25 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_line_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='line_items',
            new_name='lineitems',
        ),
    ]
