# Generated by Django 5.0.1 on 2024-02-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_subscribed_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
