# Generated by Django 5.0.1 on 2024-02-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
