# Generated by Django 5.0.1 on 2024-02-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
