# Generated by Django 5.0.1 on 2024-02-19 13:38

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_delete_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('id_user', models.IntegerField(null=True)),
                ('phone', models.TextField(max_length=20)),
                ('street_address', models.TextField(max_length=250)),
                ('post_code', models.TextField(blank=True, max_length=20)),
                ('city', models.TextField(max_length=80)),
                ('state', models.TextField(default='', max_length=80)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
