# Generated by Django 5.0.1 on 2024-02-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='id_user',
        ),
    ]
